//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpanishVerb.DAL.SQLite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class AnkiEntities : DbContext
    {
        public AnkiEntities(string connectionString) : base(connectionString)
        {
        }

        public AnkiEntities() : base("name=AnkiEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<card> cards { get; set; }
        public virtual DbSet<col> cols { get; set; }
        public virtual DbSet<note> notes { get; set; }
        public virtual DbSet<revlog> revlogs { get; set; }
        public virtual DbSet<grave> graves { get; set; }
    }
}
