//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpanishVerb.DAL.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class card
    {
        public long id { get; set; }
        public long nid { get; set; }
        public long did { get; set; }
        public long ord { get; set; }
        public long mod { get; set; }
        public long usn { get; set; }
        public long type { get; set; }
        public long queue { get; set; }
        public long due { get; set; }
        public long ivl { get; set; }
        public long factor { get; set; }
        public long reps { get; set; }
        public long lapses { get; set; }
        public long left { get; set; }
        public long odue { get; set; }
        public long odid { get; set; }
        public long flags { get; set; }
        public string data { get; set; }
    }
}
