//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpanishVerb.DAL.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class col
    {
        public long id { get; set; }
        public long crt { get; set; }
        public long mod { get; set; }
        public long scm { get; set; }
        public long ver { get; set; }
        public long dty { get; set; }
        public long usn { get; set; }
        public long ls { get; set; }
        public string conf { get; set; }
        public string models { get; set; }
        public string decks { get; set; }
        public string dconf { get; set; }
        public string tags { get; set; }
    }
}
