//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpanishVerb.DAL.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class grave
    {
        public long usn { get; set; }
        public long oid { get; set; }
        public long type { get; set; }
    }
}
