//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpanishVerb.DAL.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class note
    {
        public long id { get; set; }
        public string guid { get; set; }
        public long mid { get; set; }
        public long mod { get; set; }
        public long usn { get; set; }
        public string tags { get; set; }
        public string flds { get; set; }
        public string sfld { get; set; }
        public long csum { get; set; }
        public long flags { get; set; }
        public string data { get; set; }
    }
}
