//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpanishVerb.DAL.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class revlog
    {
        public long id { get; set; }
        public long cid { get; set; }
        public long usn { get; set; }
        public long ease { get; set; }
        public long ivl { get; set; }
        public long lastIvl { get; set; }
        public long factor { get; set; }
        public long time { get; set; }
        public long type { get; set; }
    }
}
